#!/bin/bash

# Enables SPI0 and SPI1 on device tree for BeagleBone Black and Angstrom Linux.

# Warning! On the newest angstrom image there is no dtc in opkg available.
# A simple solution is to create the compiled dtbo file on a desktop ubuntu machine
# and copy it to the BBB.

cat /sys/devices/bone_capemgr.9/slots

# Compile overlay.
if [ -n "$1" ]
then
        dtc -O dtb -o BB-SPI1-01-00A0.dtbo -b 0 -@ BB-SPI1-01-00A0.dts
        dtc -O dtb -o BB-SPI0-01-00A0.dtbo -b 0 -@ BB-SPI0-01-00A0.dts
fi

# Copy compiled file.
cp BB-SPI1-01-00A0.dtbo /lib/firmware/
cp BB-SPI0-01-00A0.dtbo /lib/firmware/

# Enable overlay
echo BB-SPI1-01 > /sys/devices/bone_capemgr.*/slots
echo BB-SPI0-01 > /sys/devices/bone_capemgr.*/slots

# Add manualy to uEnv.txt
# mkdir /mnt/boot
# mount /dev/mmcblk0p1 /mnt/boot
# capemgr.enable_partno=<name>

cat /sys/devices/bone_capemgr.9/slots

